//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernLightsHospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthernLightsHospitalEntities : DbContext
    {
        public NorthernLightsHospitalEntities()
            : base("name=NorthernLightsHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assurance> Assurances { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAdmission> tblAdmissions { get; set; }
        public virtual DbSet<tblDept> tblDepts { get; set; }
        public virtual DbSet<tblLit> tblLits { get; set; }
        public virtual DbSet<tblLitType> tblLitTypes { get; set; }
        public virtual DbSet<tblMedecin> tblMedecins { get; set; }
        public virtual DbSet<tblParent> tblParents { get; set; }
        public virtual DbSet<tblPatient> tblPatients { get; set; }
    }
}
