//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernLightsHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmission
    {
        public int IDadmission { get; set; }
        public Nullable<int> NAS { get; set; }
        public System.DateTime dateAdmis { get; set; }
        public int IDmedecin { get; set; }
        public int Lit { get; set; }
        public Nullable<bool> Chirugie { get; set; }
        public Nullable<System.DateTime> dateChirugie { get; set; }
        public Nullable<System.DateTime> dateConge { get; set; }
        public Nullable<bool> tv { get; set; }
        public Nullable<bool> telephone { get; set; }
    
        public virtual tblLit tblLit { get; set; }
        public virtual tblMedecin tblMedecin { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
